apiVersion: v1
kind: Pod
metadata:
  name: sprintpod
  labels:
    app: sprintdev
spec:
  containers:
  - image: devopscicd1234.azurecr.io/sprintacrfinaldev
    name: sprint-image
    ports:
    - containerPort: 80
      protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: sprintsvcdev
spec:
  selector:
    app: sprintdev
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sprintingress
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/override-frontend-port: "80"
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          service:
            name: sprintsvcdev
            port: 
              number: 80
        pathType: Exact
